-- Seed project data from user request
INSERT INTO public.projects (code, name, location, status, owner, type, package, start_date, end_date, description, area, budget, progress, plan_progress)
VALUES 
(
    'P-GREENSHADE', 
    'Nhà máy rèm Greenshade', 
    'Hà Nam', 
    'active', 
    'Công ty Cổ phần Lux Decor Việt Nam', 
    'Công trình công nghiệp, Hệ thống cơ điện', 
    'Tổng thầu Thiết kế và Thi công', 
    '2025-01-01', 
    '2025-06-30', 
    'Đơn vị tư vấn: Intertek Việt Nam. Tiến độ thi công: 180 ngày.', 
    '10.000m2', 
    45000000000, 
    20, 
    25
),
(
    'P-BROTHER', 
    'Nhà máy Brother', 
    'KCN Phúc Điền - Cẩm Giàng - Hải Dương', 
    'completed', 
    'Công ty TNHH Brother Industries Việt Nam', 
    'Công trình công nghiệp', 
    'Thi công nhà máy Brother', 
    '2020-03-01', 
    '2020-11-30', 
    'Đơn vị thực hiện: VIJAKO. Tổng thầu: ENCO Industry.', 
    NULL, 
    NULL, 
    100, 
    100
),
(
    'P-TCI-PRECISION', 
    'Nhà máy TCI Precision', 
    'KCN Hòa Phú - Bắc Giang', 
    'completed', 
    'Công ty Cổ phần TCI Precision', 
    'Công trình công nghiệp', 
    'Thi công xây dựng nhà máy TCI Precision', 
    '2021-07-01', 
    '2021-12-31', 
    'Đơn vị thực hiện: VIJAKO. Tổng thầu: ENCO Industry.', 
    NULL, 
    NULL, 
    100, 
    100
),
(
    'P-DREAM-RESIDENCE', 
    'Khách sạn Hà Nội Dream Residence', 
    '64 Nguyễn Lương Bằng, Đống Đa, Hà Nội', 
    'completed', 
    'Công ty TNHH Khách sạn Dịch vụ Hà Nội Dream Residence', 
    'Công trình dân dụng', 
    'Thi công khách sạn Hà Nội Dream Residence', 
    '2015-12-01', 
    '2017-02-28', 
    'Quy mô 1 hầm, 10 tầng, 70 căn hộ cao cấp.', 
    NULL, 
    NULL, 
    100, 
    100
),
(
    'P-GAMUDA-ZEN', 
    'The Zen – Gamuda Garden', 
    'Hoàng Mai, Hà Nội', 
    'completed', 
    'Công ty TNHH Gamuda Land Việt Nam', 
    'Hạ tầng kỹ thuật cảnh quan', 
    'Thi công cảnh quan trên mái block A, B, C, hoàn thiện sơn ngoài.', 
    '2018-12-01', 
    '2019-06-30', 
    'Gồm 3 tòa căn hộ cao 28-33 tầng, ~927 căn hộ. Tổng thầu: Phục Hưng Holdings.', 
    NULL, 
    NULL, 
    100, 
    100
)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    location = EXCLUDED.location,
    status = EXCLUDED.status,
    owner = EXCLUDED.owner,
    type = EXCLUDED.type,
    package = EXCLUDED.package,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    description = EXCLUDED.description,
    area = EXCLUDED.area,
    budget = EXCLUDED.budget,
    progress = EXCLUDED.progress,
    plan_progress = EXCLUDED.plan_progress;
